apiVersion: v1
kind: Secret
metadata:
  name: securebank-backend-secret
  namespace: securebank-dev
  labels:
    app.kubernetes.io/name: securebank-backend
    app.kubernetes.io/part-of: securebank
    securebank.io/environment: dev
type: Opaque
stringData:
  DATABASE_URL: "sqlite:////tmp/securebank-dev.db"
