apiVersion: v1
kind: ConfigMap
metadata:
  name: securebank-backend-config
  namespace: securebank-dev
  labels:
    app.kubernetes.io/name: securebank-backend
    app.kubernetes.io/part-of: securebank
    securebank.io/environment: dev
data:
  FLASK_ENV: "development"
  APP_NAME: "securebank-api"
  APP_VERSION: "0.1.0"
  LOG_LEVEL: "INFO"
