apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: securebank-frontend
  namespace: securebank-dev
  labels:
    app: securebank-frontend
    app.kubernetes.io/name: securebank-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: securebank
    securebank.io/environment: dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: securebank-frontend
