apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - backend-pdb.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-hpa.yaml
  - frontend-pdb.yaml
  - default-deny-ingress.yaml
  - allow-frontend-to-backend.yaml
  - allow-backend-to-postgres.yaml
  - allow-dns-egress.yaml
  - allow-frontend-egress-to-backend.yaml
  - allow-backend-egress-to-postgres.yaml
  - securebank-ingress.yaml
  - allow-traefik-to-frontend.yaml
