apiVersion: v1
kind: Secret
metadata:
  name: securebank-postgres-secret
  namespace: securebank-dev
  labels:
    app: securebank-postgres
    app.kubernetes.io/name: securebank-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: securebank
    securebank.io/environment: dev
type: Opaque
stringData:
  POSTGRES_DB: securebank
  POSTGRES_USER: securebank_user
  POSTGRES_PASSWORD: securebank_password
