apiVersion: v1
kind: Namespace
metadata:
  name: securebank-dev
  labels:
    name: securebank-dev
    app.kubernetes.io/part-of: securebank-platform
    securebank.io/tier: application
    securebank.io/environment: dev
    istio-injection: enabled
